# Generated by Django 3.2.2 on 2021-05-25 11:13

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0022_alter_pagetranslation_title"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="page",
            name="page_p_meta_idx",
        ),
        migrations.RemoveIndex(
            model_name="page",
            name="page_meta_idx",
        ),
        migrations.RemoveIndex(
            model_name="pagetype",
            name="pagetype_p_meta_idx",
        ),
        migrations.RemoveIndex(
            model_name="pagetype",
            name="pagetype_meta_idx",
        ),
        migrations.AddIndex(
            model_name="page",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title", "slug"], name="page_page_title_964714_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="pagetype",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "slug"], name="page_pagety_name_7c1cb8_gin"
            ),
        ),
    ]
